app/views.py
import email
from http import HTTPStatus
from flask import (
    Blueprint,
    render_template,
    redirect,
    url_for,
    request,
    session,
    flash,
    abort,
)
from flask_sqlalchemy import SQLAlchemy
from app.models import User, Song, Post, db, Follow, Like
from app import login_manager
from flask_login import login_required, login_user, logout_user, current_user
from app.search import YTSearch, LastFMSearch
from flask import current_app as app
from sqlalchemy import exc, or_, select
from .pagination import pagination
import app.forms
from app.helpers import get_user

main = Blueprint("main", __name__)

login_manager.login_view = "main.login"
login_manager.login_message_category = "danger"


@login_manager.user_loader
def load_user(user_id):
    try:
        return User.query.get(user_id)
    except exc.SQLAlchemyError:
        return None


@main.route("/login", methods=["GET", "POST"])
def login():
    form = app.forms.LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        if User.query.filter_by(username=username).first():
            user = User.authenticate(form.username.data, form.password.data)
            if user:
                if form.remember.data:
                    login_user(user, remember=True)
                else:
                    login_user(user)
                flash(f"Welcome back {username}", "success")

                next = request.args.get("next")
                # need to implement is_safe_url function for safe redirects
                return redirect(next or url_for(".root"))
            flash("Invalid credentials", "danger")
        else:
            flash("Username not found", "danger")
    return render_template("login.html", form=form)


@main.route("/logout")
def logout():
    logout_user()
    return redirect(url_for(".root"))


@main.route("/signup", methods=["GET", "POST"])
def signup():
    form = app.forms.SignupForm()

    if form.validate_on_submit():
        try:
            if form.avatar.data == "":
                avatar = None
            else:
                avatar = form.avatar.data
            new_user = User.signup(
                username=form.username.data,
                password=form.password.data,
                email=form.email.data,
                avatar=avatar,
                bio=form.bio.data,
            )
            db.session.commit()
            flash("Welcome to Check Out This Song!", "success")

        except exc.IntegrityError as error:
            if "username" in str(error.orig):
                flash("That username is already taken!", "danger")
            if "email" in str(error.orig):
                flash(
                    "An account already exists for that email address please login",
                    "warning",
                )

            return render_template("signup.html", form=form)

        login_user(new_user)
        return redirect(url_for(".root"))

    else:
        return render_template("signup.html", form=form)


@main.route("/")
def root():
    if request.args:
        page = int(request.args.get("p"))
        pages = pagination(page)
    else:
        page = 0
        pages = pagination(page)
    if current_user.is_authenticated:
        following_ids_query = db.session.execute(
            select([Follow.user_followed]).where(
                Follow.user_following == current_user.id
            )
        )
        following_ids = [id[0] for id in following_ids_query]
        posts = (
            Post.query.filter(
                or_(Post.user_id.in_(following_ids), Post.user_id == current_user.id)
            )
            .order_by(Post.timestamp.desc())
            .slice(pages["first_post_index"], (pages["last_post_index"] + 1))
        )
    else:
        posts = Post.query.order_by(Post.timestamp.desc()).slice(
            pages["first_post_index"], (pages["last_post_index"] + 1)
        )

    num_posts = posts.count()
    return render_template(
        "home.html",
        posts=posts,
        page=page,
        items_per_page=pages["items_per_page"],
        num_posts=num_posts,
    )


@main.route("/users/<username>")
def user_details(username):
    try:
        (match, user) = get_user(username, current_user)
    except:
        abort(404)
    posts = (
        Post.query.filter_by(user_id=user.id).order_by(Post.timestamp.desc()).limit(1)
    )
    follow_count = Follow.query.filter_by(user_followed=user.id).count()
    following_count = Follow.query.filter_by(user_following=user.id).count()
    liked_count = Like.query.filter_by(user_id=user.id).count()
    return render_template(
        "user_details.html",
        user=user,
        match=match,
        posts=posts,
        follow_count=follow_count,
        following_count=following_count,
        liked_count=liked_count
    )


@main.route("/users/<username>/followers")
def user_followers(username):
    try:
        (match, user) = get_user(username, current_user)
    except:
        abort(404)
    followers = user.followers
    follow_count = Follow.query.filter_by(user_followed=user.id).count()
    following_count = Follow.query.filter_by(user_following=user.id).count()
    liked_count = Like.query.filter_by(user_id=user.id).count()
    return render_template(
        "user_followers.html",
        user=user,
        match=match,
        followers=followers,
        follow_count=follow_count,
        following_count=following_count,
        liked_count=liked_count
    )


@main.route("/users/<username>/following")
def user_following(username):
    try:
        (match, user) = get_user(username, current_user)
    except:
        abort(404)
    following = user.following
    follow_count = Follow.query.filter_by(user_followed=user.id).count()
    following_count = Follow.query.filter_by(user_following=user.id).count()
    liked_count = Like.query.filter_by(user_id=user.id).count()
    return render_template(
        "user_following.html",
        user=user,
        match=match,
        following=following,
        follow_count=follow_count,
        following_count=following_count,
        liked_count=liked_count
    )


@main.route("/users/<username>/likes")
def user_likes(username):
    try:
        (match, user) = get_user(username, current_user)
    except:
        abort(404)
    likes = user.liked_posts
    follow_count = Follow.query.filter_by(user_followed=user.id).count()
    following_count = Follow.query.filter_by(user_following=user.id).count()
    liked_count = Like.query.filter_by(user_id=user.id).count()
    return render_template(
        "likes.html",
        user=user,
        match=match,
        likes=likes,
        follow_count=follow_count,
        following_count=following_count,
        liked_count=liked_count
    )


@main.route("/edit-profile", methods=["GET", "POST"])
@login_required
def edit_user():
    form = app.forms.SignupForm(obj=current_user)
    if form.validate_on_submit():
        user = User.authenticate(current_user.username, form.password.data)
        if user:
            form.populate_obj(user)
            db.session.commit()
            flash("Profile saved successfully", "success")
            return redirect(url_for(".user_details", username=user.username))
        flash("Incorrect password", "danger")
    return render_template("edit_user.html", form=form, user=current_user)


@main.route("/usersearch")
def user_search():
    if request.args:
        query = request.args.get("q")
        results = User.query.filter(User.username.like("%" + query + "%")).slice(0, 15)
    else:
        query = None
        results = None
    return render_template("user_search.html", query=query, results=results)


@main.route("/search", methods=["GET", "POST"])
@login_required
def search():
    form = app.forms.SongSearchForm()

    if form.validate_on_submit():
        query = form.search.data
        return redirect(url_for(".search_results", q=query))
    else:
        return render_template("songsearch.html", form=form)


@main.route("/search-results")
@login_required
def search_results():
    query = request.args.get("q")
    lfm = LastFMSearch(query)
    matches = lfm.matches

    form = app.forms.SongSelectForm()

    return render_template(
        "search-results.html", matches=matches, query=query, form=form
    )


@main.route("/video-select", methods=["GET", "POST"])
@login_required
def video_select():
    match = dict(title="", artist="")
    form = app.forms.SongSelectForm(obj=match)

    if form.validate_on_submit():
        match["title"] = form.title.data
        match["artist"] = form.artist.data
        match["lastfm_entry"] = form.lastfm_entry.data
        yt = YTSearch(match["title"] + " " + match["artist"])
        yt_matches = yt.matches
        yt_submit = app.forms.YTSubmitForm()
        session["new_song"] = match
        return render_template(
            "video_select.html", match=match, yt_matches=yt_matches, yt_submit=yt_submit
        )
    else:
        return redirect(url_for(".search"))


@main.route("/create-post", methods=["GET", "POST"])
@login_required
def create_post():
    new_song = session["new_song"]
    form = app.forms.YTSubmitForm(obj=new_song)

    if form.validate_on_submit():
        new_song["youtube_url"] = form.youtube_url.data
        session["new_song"] = new_song
        post_form = app.forms.PostSubmitForm()
        return render_template("create_post.html", song=new_song, post_form=post_form)
    else:
        return redirect(url_for(".search"))


@main.route("/confirm-post", methods=["GET", "POST"])
@login_required
def confirm_post():
    post_form = app.forms.PostSubmitForm()

    if post_form.validate_on_submit():
        description = post_form.description.data
        new_song = session["new_song"]
        user = User.query.get_or_404(current_user.id)
        session["post_desc"] = description
        return render_template(

app/templates/503.html
{% extends 'base.html' %}

{% block content %}
<section class="hero is-large">
    <div class="hero-body">
        <p class="title" id="error-503">
            503 Not Authorized!
        </p>
        <p class="subtitle">
            Sorry, it looks like you don't have permission for that, make sure you're logged in or check where you're going!
        </p>
    </div>
</section>
{% endblock %}

app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<div class="columns is-tablet is-centered">
    <div class="column is-half">
        <div class="container is-half">
            <h1 class="title">About Check Out This Song</h1>
            <p class="block">
                Check out this song is a project by Yara Beadenkopf, built for their capstone project while going through Springboard's full stack software engineering bootcamp. <i>COTS</i> is heavily inspired by <a href="https://www.thisismyjam.com/">This is My Jam</a>, a social music sharing site that is sadly no longer active. You can find out more about the project on github:
            </p>
            <p class="block">
                <a href="https://github.com/dixls/check-out-this-song">https://github.com/dixls/check-out-this-song</a>
            </p>
            <p class="block">
                Enjoy!
            </p>
        </div>
    </div>
</div>
{% endblock %}

app/templates/create-post.html
{% extends 'base.html' %}

{% block content %}
{% if matches %}
<h1 class="title">Results for '<i>{{query}}</i>'</h1>
<div class="columns is-multiline is-centered">
    {% for match in matches[:5] %}
    <div class="column is-three-quarters">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-left">
                        <figure class="image is-48x48">
                            <img src="{{match['image'][1]['#text']}}" alt="">
                        </figure>
                    </div>
                    <div class="media-content">
                        <p class="title">{{match['name']}}</p>
                        <p class="subtitle"><i>by</i> {{match['artist']}}</p>
                    </div>
                    <div class="media-right">
                        <span class="icon is-large">
                            <a href="#" class="has-text-success">
                                <i class="fas fa-2x fa-check-square"></i>
                            </a>
                        </span>
                    </div>
                </div>
                <!-- <div class="content">
                    {{match}}
                </div> -->
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
no matches found
{% endif %}
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% block content %}
<section class="hero">
    <div class="hero-body ">
        <h1 class="title is-2 has-text-weight-bold">
            Check Out This Song!
        </h1>
        <p class="subtitle">
            A nice place to share songs with your friends!
        </p>
    </div>
</section>
{% if num_posts == 0 %}
        <section class="hero is-medium">
            <div class="hero-body">
                <p class="title is-2">It doesn't look like you're following anyone</p>
                <p class="subtitle">Try <a href="{{url_for('main.user_search')}}">searching for someone to follow</a></p>
            </div>
        </section>
        {% endif %}
<div class="columns is-tablet is-centered">
    <div class="column is-half">
        {% if posts %}
        {% for post in posts[:items_per_page] %}
        {% include 'post_card.html' %}
        {% endfor %}
        {% endif %}
        {% include 'pagination.html' %}
    </div>
</div>
{% endblock %}

app/templates/likes.html
{% extends 'base.html' %}

{% block content %}
<div class="columns is-tablet is-centered">
    <div class="column is-half">
        {% include 'user_details_top.html' %}
            <div class="card-block">
                <h2 class="card-header-title is-4">Posts {{user.username}} has liked</h2>
            </div>
        {% if likes %}
        {% for post in likes %}
        {% include 'post_card.html' %}
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/nav.html
<nav class="navbar is-dark mb-3" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        Check Out This Song!
      </a>
  
      <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a href="{{url_for('main.search')}}" class="navbar-item">
          Submit a Song
        </a>
        <a href="{{url_for('main.user_search')}}" class="navbar-item">
          Search Users
        </a>
        <a href="{{url_for('main.about')}}" class="navbar-item">
          About
        </a>
      </div>
  
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            {% if current_user.is_authenticated %}
            <a href="/users/{{current_user.username}}" class="navbar-item button is-dark">
              <div class="level">
                <figure class="image is_24x24 m-1 is-hidden-mobile">
                  <img src="{{current_user.avatar}}" alt="">
                </figure>
                <span class="m-1">
                  {{current_user.username}}
                </span>
              </div>
            </a>
            <a class="button navbar-item is-dark" href="{{url_for('main.logout')}}">
              Log out
            </a>
            {% else %}
            <a class="button is-primary" href="{{url_for('main.signup')}}">
              <strong>Sign up</strong>
            </a>
            <a class="button is-dark" href="{{url_for('main.login')}}">
              Log in
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>

app/templates/pagination.html
<div class="columns is-centered">
    {% if page %}
        <div class="column has-text-centered">
            {% if page == 1 %}
            <a href="/" class="button">
            {% else %}
            <a href="/?p={{page-1}}" class="button">
            {% endif %}
                <span class="icon">
                    <i class="fas fa-angle-left"></i>
                </span>
                <span>
                    Newer
                </span>
            </a>
        </div>
        <div class="column"></div>
        {% if num_posts < items_per_page %}
            <div class="column"></div>
        {% else %}
            <div class="column has-text-centered">
                <a href="/?p={{page+1}}" class="button">
                    <span>
                        Older
                    </span>
                    <span class="icon">
                        <i class="fas fa-angle-right"></i>
                    </span>
                </a>
            </div>
        {% endif %}
    {% else %}
        <div class="column"></div>
        <div class="column"></div>
        {% if num_posts <= items_per_page %}
            <div class="column"></div>
        {% else %}
        <div class="column has-text-centered">
            <a href="/?p=1" class="button">
                <span>
                    Older
                </span>
                <span class="icon">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
        {% endif %}
    {% endif %}
</div>

app/templates/post_card.html
<div class="card m-3" id="{{post.id}}">
    <div class="card-title m-0 p-2">
        <div class="level">
            <div class="level-left">
                <div class="level-item">
                    <div>
                        <p class="title is-4">{{ post.song.title }}</p>
                        <p class="heading is-6 m-0">by {{ post.song.artist }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-image">
        {% include 'yt-embed-feed.html' %}
    </div>
    <div class="media p-2 m-0">
        <div class="media-left">
            <figure class="image is-48x48">
                <a href="/users/{{post.user.username}}">
                    <img src="{{ post.user.avatar }}" alt="">
                </a>
            </figure>
        </div>
        <div class="media-content">
            <p class="heading is-6 is-italic p-0 m-0">shared by</p>
            <a href="/users/{{post.user.username}}">
            <p class="title is-4">{{ post.user.username }}</p>
            </a>
        </div>
        <div class="media-right">
            <div class="level">
                <div class="level-right">
                    <div class="level-item">
                        <div>
                            <p class="level-right heading is-6 is-italic">posted on</p>
                            <p class="level-right heading is-6">{{ post.date_format() }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-content">
       
        <div class="content">
            <p>{{ post.description }}</p>
        </div>
    </div>
    {% if current_user.is_authenticated %}
    <footer class="card-footer">
        {% if current_user == post.user or current_user.admin %}
        <a class="card-footer-item delete-button">
            <span>
                <i class="fas fa-trash"></i>
            </span>
        </a>
        {% endif %}
        {% if post in current_user.liked_posts %}
        <a class="card-footer-item unlike-button has-text-danger">
        {% else %}
        <a class="card-footer-item like-button">
        {% endif %}
            <span>
                <i class="fas fa-heart"></i>
            </span>
        </a>
        
    </footer>
    {% endif %}
</div>

app/templates/search-results.html
{% extends 'base.html' %}

{% block content %}
{% if matches %}
<h1 class="title">Results for '<i>{{query}}</i>'</h1>
<span class="icon is-large">
    <a href="{{url_for('main.search')}}">
        <i class="fas fa-2x fa-angle-left"></i>
    </a>
</span>
<div class="columns is-multiline is-centered">
    {% for match in matches[:5] %}
    <div class="column is-three-quarters">
        <div class="card">
            <div class="card-content">
                <div class="media">
                    <div class="media-left">
                        <figure class="image is-48x48">
                            <img src="{{match['image'][1]['#text']}}" alt="">
                        </figure>
                    </div>
                    <div class="media-content">
                        <p class="title">{{match['name']}}</p>
                        <p class="subtitle"><i>by</i> {{match['artist']}}</p>
                    </div>
                    <form action="{{url_for('main.video_select')}}" method="post">
                        {{ form.csrf_token }}
                        {{ form.title(value_=match['name']) }}
                        {{ form.artist(value_=match['artist']) }}
                        {{ form.lastfm_entry(value_=match['url']) }}
                        <div class="media-right">
                            <button type="submit" class="button is-success">
                                <span class="icon is-large">
                                    <i class="fas fa-2x fa-check"></i>
                                </span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
no matches found
{% endif %}
{% endblock %}

app/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="columns is-tablet is-centered">
    <div class="column is-half">
        <p class="title has-text-centered">Sign up for Check Out This Song!</p>
        <div class="card m-2">
            <div class="card-content">
                <form method="POST">
                    <div class="field">
                        {{ form.csrf_token }}
                        {{ form.username.label(class_="label") }}
                        {{ form.username(class_="input", placeholder_="username") }}
                        {% for error in form.username.errors %}
                        <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                    <div class="field">
                        {{ form.email.label(class_="label") }}
                        {{ form.email(class_="input", placeholder_="user@domain.com") }}
                        {% for error in form.email.errors %}
                        <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                    <div class="field">
                        {{ form.password.label(class_="label") }}
                        {{ form.password(class_="input", placeholder_="password") }}
                        {% for error in form.password.errors %}
                        <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                    <div class="field">
                        {{ form.avatar.label(class_="label") }}
                        {{ form.avatar(class_="input", placeholder_="https://domain.com/image.jpg") }}
                        {% for error in form.avatar.errors %}
                        <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                    <div class="field">
                        {{ form.bio.label(class_="label") }}
                        {{ form.bio(class_="input textarea", rows_="3", placeholder_="I love music!") }}
                        {% for error in form.bio.errors %}
                        <p class="help is-danger">{{ error }}</p>
                        {% endfor %}
                    </div>
                    <button type="submit" class="button is-success">Sign Up!</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/user_following.html
{% extends 'base.html' %}

{% block content %}
<div class="columns is-tablet is-centered">
    <div class="column is-half">
        {% include 'user_details_top.html' %}
        <div class="card m-3">
            <div class="card-block">
                <h2 class="card-header-title is-4">Users {{user.username}} is following</h2>
            </div>
        {% if following %}
        {% for user in following %}
        {% include 'user_row.html' %}
        {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/user_row.html
    <div class="card-block">
        <div class="card-content">
            <a href="/users/{{user.username}}">
            <div class="media p-2 m-0">
                <div class="media-left">
                    <figure class="image is-48x48">
                        <img src="{{ user.avatar }}" alt="">
                    </figure>
                </div>
                <div class="media-content">
                    <a href="/users/{{user.username}}">
                    <p class="title is-4">{{ user.username }}</p>
                </div>
                {% if current_user.is_authenticated %}
                {% if user != current_user %}
                    {% if user in current_user.following %}
                    <a class="button is-primary is-outlined unfollow-button" id="{{user.id}}">
                        <span>
                            Unfollow
                        </span>
                        <span class="icon">
                            <i class="fas fa-minus"></i>
                        </span>
                    </a>
                    {% else %}
                    <a  class="button is-primary follow-button" id="{{user.id}}">
                        <span>
                            Follow
                        </span>
                        <span class="icon">
                            <i class="fas fa-plus"></i>
                        </span>
                    </a>
                    {% endif %}
                {% endif %}
                {% endif %}
            </div>
            </a>
        </div>
    </div>

app/templates/video_select.html
{% extends 'base.html' %}

{% block content %}
<span class="icon is-large">
    <a href="{{url_for('main.search')}}">
        <i class="fas fa-2x fa-angle-left"></i>
    </a>
</span>
<h1 class="title">Select a video for <i>{{match.title}}</i> by {{match.artist}}</h1>
<div class="columns is-multiline is-centered">
    {% if yt_matches %}
    {% for video in yt_matches %}
    <div class="column is-full-phone is-one-quarter">
        <div class="card">
            <div class="card-image">
                <figure class="image">
                    <div class="container" style="position:relative; padding-bottom: 56.25%; padding-top: 30px; max-width: 100%; height:0; overflow:hidden">
                    <iframe style="position:absolute; top: 0; left: 0; width:100%; height:100%" src="https://www.youtube.com/embed/{{video['id']['videoId']}}" title="YouTube video player"
    frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen></iframe>
                    </div>
                </figure>
            </div>
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">{{video['snippet']['title']}}</p>
                        <p class="subtitle is-6"><i>uploaded by</i> {{video['snippet']['channelTitle']}}</p>
                    </div>
                </div>
                <form action="{{url_for('main.create_post')}}" method="post">
                    {{ yt_submit.csrf_token }}
                    {{ yt_submit.youtube_url(value_=video['id']['videoId']) }}
                    <button type="submit" class="button is-success">
                        <span class="icon is-large">
                            <i class="fas fa-plus"></i>
                        </span>
                        <span>
                            Select this video
                        </span>
                    </button>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% else %}
no matches found
{% endif %}
{% endblock %}

app/templates/yt-embed.html
<div class="container" style="position:relative; padding-bottom: 56.25%; padding-top: 30px; max-width: 100%; height:0; overflow:hidden">
    <iframe style="position:absolute; top: 0; left: 0; width:100%; height:100%"
        src="https://www.youtube.com/embed/{{song.youtube_url}}" title="YouTube video player" frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen></iframe>
</div>